# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='посилання')),
                ('excerpt', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='коротикий зміст статті')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='повний зміст статті')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата публікації')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='дата редагування')),
                ('publish', models.BooleanField(default=True, verbose_name='опублікована')),
            ],
            options={
                'verbose_name_plural': 'статті',
                'verbose_name': 'статтю',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name_plural': 'теги',
                'verbose_name': 'тег',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='теги'),
        ),
    ]
